### ISSUE TITLE
404 for frontend.js with include_ember_script_tags :frontend

### ISSUE THREAD

**Issue by sevab** [thoughtbot/ember-cli-rails#311]
I'm loading my ember app only inside some of my rails views via `include_ember_script_tags :frontend`. However, upon starting the server I get a 404 for `frontend.js`.

The issue is solved by a hack where I temporarily add `mount_ember_app :frontend, to: "/"` on top of `routes.rb` and reload the page, which presumably triggers ember to build the assets. Upon first reload I get a blank page because the assets are obviously not built yet, and upon the second reload I get a blank page because the route is caught by `mount_ember_app :frontend, to: "/"`, which tries and fails to load `tmp/../apps/frontend/index.html`. But now that assets have been built, removing `mount_ember_app` from routes lets me load my intended rails view as well as `frontend.js`.

Any changes to ember app's files after this successfully trigger rebuilding of the asset, but not before the hack has been made.

The issue has only appeared after updating from v0.3.5 to 0.5.6.

**Comment by seanpdoyle** [comment]
Thanks for opening this issue and bringing this to our attention!

This issue sounds like a duplicate of #298, so I'm closing it, since it's already on our radar.

As a potential quick-fix (if a fix is time-sensitive), try this out:

https://github.com/thoughtbot/ember-cli-rails/issues/298#issuecomment-159352737

**Comment by sevab** [comment]
As I understand `sd-manifest` has now been merged into master https://github.com/rondale-sc/ember-cli-rails-addon/pull/23, so I have updated the gem to `0.5.8` and `ember-cli-rails-addon 0.5.2`, but the issue remains.

**Comment by sevab** [comment]
Worth noting that I haven't actually tested `sd-manifest` back when the issue occurred, so I'm not sure whether it fixed my issue in the first place.

**Comment by seanpdoyle** [comment]
@sevab those changes have probably already been removed in the latest release.

I'm working on releasing `0.6.x` with some breaking changes that simplifies everything.

I'll also be updating an example repository that will hopefully clarify how the library is to be used.

Updates are forthcoming...

**Comment by sevab** [comment]
@seanpdoyle thank you!

**Comment by seanpdoyle** [comment]
@sevab would you mind trying out:

* https://github.com/thoughtbot/ember-cli-rails/tree/remove-sprockets for `ember-cli-rails` gem
* https://github.com/rondale-sc/ember-cli-rails-addon/tree/remove-sprockets for `ember-cli-rails-addon`

Each of those branches has up-to-date README's.

**Comment by sevab** [comment]
@seanpdoyle  Throws `EmberCli::BuildError` for `= include_ember_script_tags :frontend`

**Comment by sevab** [comment]
Sorry, didn't read the updated README yet.

**Comment by sevab** [comment]
Reading the documentation for the `remove-sprockets` branch, I'm a bit confused. Since I'm only injecting EmberCLI-generated assets selectively, do I also need to call `EmberCli.build("frontend")` in the controller actions where I inject the assets as well as `mount_ember_app :frontend` on those routes?

By only including `= include_ember_script_tags :frontend` in the views where I need the ember code, I get `EmberCli::BuildError` for `= include_ember_script_tags :frontend`. And my `ember.rb` initializer is a simple:
```ruby
EmberCli.configure do |c|
  c.app :frontend, exclude_ember_deps: 'jquery'
end
```

If I also add `EmberCli.build("frontend")` to that controller action, on the first request `= include_ember_script_tags :frontend` throws an `ActionView::Template::Error (no implicit conversion of nil into String):`, but the second request is successful in rendering the Rails views. However, ember's assets are still unavailable and when navigating to `'/my/stuff'` I get 404 for:
`GET http://localhost:3000/my/assets/vendor.js `
`GET http://localhost:3000/my/assets/frontend.js `

the assets are however compiled successfully to: `/tmp/ember-cli/apps/frontend/assets/frontend.js`, etc.

Adding `mount_ember_app :frontend, to: "/my/stuff", controller: "user_panel", action: "my"` doesn't change anything.

I did not specify any configurations for `ember-cli-rails-addon` and my `environemnts.js` is as follows:

```javascript
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'frontend',
    environment: environment,
    baseURL: '/',
    ...
```

Also, I've submitted a pull request for some typos in README.md.

**Comment by seanpdoyle** [comment]
> do I also need to call EmberCli.build("frontend") in the controller actions where I inject the assets as well as mount_ember_app :frontend on those routes?

 yes, the call to `mount_ember_app` is necessary no matter the type of helper used in the view.

> If I also add EmberCli.build("frontend") to that controller action, on the first request = include_ember_script_tags :frontend throws an ActionView::Template::Error (no implicit conversion of nil into String):, but the second request is successful in rendering the Rails views. 

Does it still error when you use:

1. `mount_ember_app :frontend, to: "/the-frontend-path", controller: "the_frontend_controller"`
1. `EmberCli.build(:frontend)` in the controller action
1. `include_ember_script_tag :frontend` in the view

If so, would you mind sharing the stack trace?

Are you using the matching `remove-sprockets` branch of the addon?

**Comment by seanpdoyle** [comment]
I'm hopeful we can get this fix landed and stabilize things for you.

Having said that, we don't plan on supporting the `include_ember_*_tags` helpers in post-`1.0.0` versions of this gem.

It is likely they'll be extracted to a stable gem, but I highly recommend you migrate toward using the `render_ember_app` helper, which relies 100% on EmberCLI to generate the page's HTML.

**Comment by sevab** [comment]
Yep, using `"ember-cli-rails-addon": "rondale-sc/ember-cli-rails-addon#remove-sprockets"`.

Following the 3 steps and also including `<base href="/">` in the view still getting 404s on `http://localhost:3000/assets/frontend.js` & `vendor.js`

Stack trace:
```
Started GET "/assets/frontend.js" for ::1 at 2015-12-10 04:13:19 +0000
[2015-12-10 04:13:19] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:19
	/Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `eof?'
	/Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `run'
	/Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

ActionController::RoutingError (No route matches [GET] "/assets/frontend.js"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Yep, planning to migrate everything to Ember-CLI in the next month or two!

**Comment by seanpdoyle** [comment]
@sevab would you be comfortable granting me access to the problem application?

If not, would you mind trying to reproduce the bug in a sample application?

**Comment by seanpdoyle** [comment]
@sevab The second commit of https://github.com/seanpdoyle/ember-cli-rails-heroku-example/tree/remove-sprockets

https://github.com/seanpdoyle/ember-cli-rails-heroku-example/commit/529f897f15c53d95f0d33490fb8a9e52e8607fe7

Contains the entirety configuring an `include_ember_*_tags` application. (It powers https://ember-cli-rails-heroku-example.herokuapp.com/admin/)

**Comment by sevab** [comment]
Tried reproducing in a sample app, but everything actually worked, so it's probably something with the asset pipeline in my main app, will investigate and report any findings.

In the meantime in both `v0.5.8` and `remove-sprockets` branch, command `rails generate ember:init` throws `Could not find generator 'ember:init'. Maybe you meant 'ember:init' or 'ember:heroku' or 'erb:mailer' Run `rails generate --help` for more options.`

Though `rails generate ember-cli:init` successfully generated the initializer in `0.5.8`, but not in `remove-sprockets`. So README probably needs to be updated to use `$ rails generate ember-cli:init`

**Comment by seanpdoyle** [comment]
@sevab thanks for all this information!

the generator namespace rename landed in https://github.com/thoughtbot/ember-cli-rails/commit/0eebed8ca8859c28bbe10633b7dc3d7b24bd999a.

`remove-sprockets` was then rebased to include that commit.

Do you still get those errors if you `bundle update ember-cli-rails`?

**Comment by seanpdoyle** [comment]
> so it's probably something with the asset pipeline in my main app, will investigate and report any findings.

**NOT** depending on integrating with the asset pipeline is the entire reason for the `remove-sprockets` branch!

**Comment by sevab** [comment]
`rails generate ember:init` throws an error for both
`gem "ember-cli-rails"` and `gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails", branch: "remove-sprockets"`

obviously running a `bundle update ember-cli-rails` for each.

**Comment by seanpdoyle** [comment]
@sevab have you tried running `spring stop` before the generator?

**Comment by seanpdoyle** [comment]
@sevab fixed in https://github.com/thoughtbot/ember-cli-rails/pull/345

**Comment by sevab** [comment]
Great!

Yep, `spring stop` didn't help.

**Comment by seanpdoyle** [comment]
@sevab generator fix has been merged and is ready to go

**Comment by sevab** [comment]
Master now works!

**Comment by sevab** [comment]
But `branch: "remove-sprockets"` throws an error:
```
/Users/.../.rvm/gems/ruby-2.2.1/bundler/gems/ember-cli-rails-9d51d9d7caff/lib/ember-cli-rails.rb:23:in `block in app': :frontend app is not defined (KeyError)
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/hash_with_indifferent_access.rb:168:in `fetch'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/hash_with_indifferent_access.rb:168:in `fetch'
	from /Users/.../.rvm/gems/ruby-2.2.1/bundler/gems/ember-cli-rails-9d51d9d7caff/lib/ember-cli-rails.rb:22:in `app'
	from /Users/.../.rvm/gems/ruby-2.2.1/bundler/gems/ember-cli-rails-9d51d9d7caff/lib/ember_cli/route_helpers.rb:17:in `mount_ember_app'
	from /Users/.../Documents/Ruby/ember-cli-rails-demo/ember-cli-rails-demo/config/routes.rb:2:in `block in <top (required)>'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/.../Documents/Ruby/ember-cli-rails-demo/ember-cli-rails-demo/config/routes.rb:1:in `<top (required)>'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/.../Documents/Ruby/ember-cli-rails-demo/ember-cli-rails-demo/config/environment.rb:5:in `<top (required)>'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application.rb:92:in `require'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application.rb:92:in `preload'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application.rb:143:in `serve'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
	from /Users/.../.rvm/gems/ruby-2.2.1/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by seanpdoyle** [comment]
@sevab would you mind sharing the example repo (and your original repo, if you'd like) with me?

> `:frontend app is not defined (KeyError)`

leads me to believe your initializer hasn't been created, or isn't executing properly.

**Comment by sevab** [comment]
Yeah, I removed `config/initializers/ember.rb` before running `rails generate ember:init` to test that it works in "remove-sprockets".

This is the sample app: https://github.com/sevab/ember-cli-rails-demo
Unfortunately, I can't share the original repo, but I'll try to find and report the problem with `include_ember_script_tags` in 10-13 hours (it's now 6am here in UK).

**Comment by seanpdoyle** [comment]
@sevab would you mind trying out https://github.com/thoughtbot/ember-cli-rails/pull/347?

It removes the need for the consumer (you) to manually invoke `EmberCli.build`.

**Comment by seanpdoyle** [comment]
@sevab `remove-sprockets` has been merged into `master`.

`master` also now contains https://github.com/thoughtbot/ember-cli-rails/commit/2b26309c075e90c6e567df85bdde8d10f135dfd9 which removes the burden you consumers manually calling `EmberCli.build`.

Would you mind trying out `master` in your application?

**Comment by sevab** [comment]
@seanpdoyle Found the issue in the original app: I wasn't mounting the ember app properly in the routes.

Having now fixed my routes I can confirm that both `0.5.8.` and `master` work well, but with `remove-sprockets` merged, master now obviously requires to include `<base href="/">`

**Comment by sevab** [comment]
@seanpdoyle I think it might be worthwhile mentioning in the **Rendering the EmberCLI generated JS and CSS** section of README that the app needs to be mounted separately on each route where the assets are included, as this was my source of confusion as I mistakenly assumed that it needs to be mounted only on `mount_ember_app :frontend, to: "/"`.

I can submit a pull request if you wish.

**Comment by sevab** [comment]
Actually, the README is pretty clear about this, I guess I just misunderstood it.

**Comment by sevab** [comment]
Also, it seems that mounting ember just once on the root route at the very bottom of `routes.rb` is enough even though I don't even include ember assets on that route.

**Comment by seanpdoyle** [comment]
@sevab an Ember app mounted to `"/"` shouldn't require `<base href="/">`.

**Comment by sevab** [comment]
@seanpdoyle for some reason the assets fail to load without `<base href="/">` even when mounted on '/'.

Also, it seems that without mounting it on the root the assets fail to load too. Mounting it on the route where I am using it (e.g. `mount_ember_app :frontend, to: 'my/stuff', controller: 'user_panel', action: 'my'`) is ignored.

**Comment by seanpdoyle** [comment]
What if you mount `to: "/my/stuff"` (note the leading `"/"`)

**Comment by sevab** [comment]
@seanpdoyle 404s on both.

**Comment by sevab** [comment]
The current solution of simply mounting it on the root at the very bottom seems like a hack, but it works.

**Comment by seanpdoyle** [comment]
> mounting it on the root at the very bottom seems like a hack, but it works.

@sevab what about that feels like a hack? 

What is the route you're serving your Ember application from?

**Comment by sevab** [comment]
the fact that I'm not including ember assets on the root route seems like hack. Also, the fact that it catches all non-existent routes and renders ember's blank `index.html` page in their place. As such I have to redirect it to a non-existent controller to have rails show users an error message telling that the route doesn't actually exist, e.g.:
```ruby
root 'existing_controller#landing_page'
mount_ember_app :frontend, to: '/', controller: 'non_existing_controller'
```

`root 'existing_controller#landing_page'` in this case makes sure that `'/'` redirects to a correct landing page and `mount_ember_app ...` takes care of all non-existent routes.

While I could implement error routing in ember.js and show users "Route doesn't exist" error via ember views, I can't currently do that since my ember app doesn't yet load on its own without being inside a rails view (e.g. jQuery and all necessary css is part of rails assets).

Again, this is not an issue, since I plan to port all the front-end to Ember-CLI in the next month or two anyways.

**Comment by sevab** [comment]
> What is the route you're serving your Ember application from?

I'm not serving the Ember app from any routes, just including ember assets selectively in some rails views via `= include_ember_script_tags :frontend`.

> What is the URL you'd like to visit to view the app?

I'm including Ember assets as part of the rails view on 'my/stuff' and some other routes. Again, everything now works with the current approach of mounting the app on root at the very bottom of `routes.rb`, even though it seems like a hack.

**Comment by seanpdoyle** [comment]
@sevab thanks for providing all that extra context!

I have a better understanding of what you're experiencing now.

> Again, this is not an issue, since I plan to port all the front-end to Ember-CLI in the next month or two anyways.

This is GREAT NEWS, since your current setup doesn't really fit into the use-cases we'd like to support.

**Comment by sevab** [comment]
@seanpdoyle thank you for all the guidance and the great work on the gem!

**Comment by seanpdoyle** [comment]
@sevab how would you feel about a routing API that is purely concerned with serving Ember's assets:

```rb
# config/routes.rb
mount_ember_assets :frontend, to: '/'
```

This would allow you to embed the `include_ember_*_tags` wherever you'd like, so long as the `<base>` tag's `href` attribute was set to the proper prefix.

For example, for serving assets from `/a/nested/page`, you'd need to either:

* `mount_ember_assets :frontend, to: '/a/nested/page/`
* include `<base href="/a/nested/page">` in the view that has your `include_` calls

**Comment by seanpdoyle** [comment]
@sevab does https://github.com/thoughtbot/ember-cli-rails/pull/352 scratch this itch?

**Comment by sevab** [comment]
@seanpdoyle wow, yes, this is much better!

**Comment by allthesignals** [comment]
I noticed the issue in comment https://github.com/thoughtbot/ember-cli-rails/issues/311#issuecomment-163488803 is still occurring with `gem "ember-cli-rails"`, requires `gem "ember-cli-rails", github: "thoughtbot/ember-cli-rails"`. Am I missing something?

Thanks!
